### ISSUE TITLE
Version 1.0 Roadmap

### ISSUE THREAD

**Issue by mikepack** [modeset/teaspoon#308]
- [x] Pull testing libraries out of core. Install would be `gem install teaspoon-mocha`. (breaking)
- [x] Support Jasmine 2.0
- [x] Support Mocha 2.0
- [x] Namespace framework-specific implementations instead of monkey patching (breaking)
- [x] Register formatters with core
- [x] Register drivers with core
- [x] Rework coverage configuration (breaking)
